version: '3.7'
services:
  app:
    image: kylecrat/rails_6_site_template:v1
    build:
      context: .
    command: ["spring", "server"]
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - RAILS_ENV
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
      - ${HOME}/.irbrc:/root/.irbrc
      - ${HOME}/.irb-history:/root/.irb-history

  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  web:
    image: kylecrat/rails_6_site_template:v1
    build:
      context: .
      dockerfile: Dockerfile
    command: foreman start -f Procfile.dev -p 3000
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - RAILS_ENV
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - pg

  webpacker:
    image: kylecrat/rails_6_site_template:v1
    command: ./bin/webpack-dev-server --host 0.0.0.0
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3035:3035

volumes:
  gems:
  pg-data:
  node-modules:
